//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetOn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetOn.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetOn by Voltura AB
        ///
        ///https://github.com/voltura/VolturaTools
        ///
        ///Free for all..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NetOn.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundMenu {
            get {
                return ResourceManager.GetString("BackgroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    !   .
        /// </summary>
        internal static string ClearThroat {
            get {
                return ResourceManager.GetString("ClearThroat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon colors.
        /// </summary>
        internal static string ColorsMenu {
            get {
                return ResourceManager.GetString("ColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisabledBackground.
        /// </summary>
        internal static string DisabledBackground {
            get {
                return ResourceManager.GetString("DisabledBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisabledForeground.
        /// </summary>
        internal static string DisabledForeground {
            get {
                return ResourceManager.GetString("DisabledForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit NetOn.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set Icon. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToSetIcon {
            get {
                return ResourceManager.GetString("FailedToSetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update color..
        /// </summary>
        internal static string FailedToUpdateColor {
            get {
                return ResourceManager.GetString("FailedToUpdateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update first day of status setting.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateDayOfWeek {
            get {
                return ResourceManager.GetString("FailedToUpdateDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update registry.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateRegistry {
            get {
                return ResourceManager.GetString("FailedToUpdateRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceRedraw.
        /// </summary>
        internal static string ForceRedraw {
            get {
                return ResourceManager.GetString("ForceRedraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string ForegroundMenu {
            get {
                return ResourceManager.GetString("ForegroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute all sounds.
        /// </summary>
        internal static string MuteAllSoundsMenu {
            get {
                return ResourceManager.GetString("MuteAllSoundsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network .
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this function is not implemented yet..
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetOn will not start with Windows.
        /// </summary>
        internal static string NotStartWithWindows {
            get {
                return ResourceManager.GetString("NotStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors reset.
        /// </summary>
        internal static string ResetColors {
            get {
                return ResourceManager.GetString("ResetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        internal static string ResetColorsMenu {
            get {
                return ResourceManager.GetString("ResetColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select background color.
        /// </summary>
        internal static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select foreground color.
        /// </summary>
        internal static string SelectForegroundColor {
            get {
                return ResourceManager.GetString("SelectForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SeparatorMenu {
            get {
                return ResourceManager.GetString("SeparatorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetOn set to start with Windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string StartWithWindowsMenu {
            get {
                return ResourceManager.GetString("StartWithWindowsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayMenu {
            get {
                return ResourceManager.GetString("WednesdayMenu", resourceCulture);
            }
        }
    }
}
